version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'website'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - website
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - website
networks:
  website:
    driver: bridge
    external: false