version: '3.9'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'website'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - website
    ports:
      - "3306:3306"
networks:
  website:
    driver: bridge
    external: false