spring:
  r2dbc:
    username: ENC(JG+fK/Tu8IM5Rr/mRXUdCFJAJ8+heBraOdMSFuintHlHj6CYN4kO1bqrTO9Errug)
    password: ENC(FSG4+3DC4TV4ElSESkPUioRSxDSor7UImWHGLF5UEqCsYgzxb5cRSo2LuPbVTRcS)
    url: ENC(07lCIV5h9w744NNaIt39Us69UaFHVPxerxcRhU6vvV852P3b8/qfXr+O6s5wLqS5nJi8jGAzoahEwp+fBEf/VV8mTM/WdSRnfAekLrLoe7w=)
logging:
  level:
    root: error