server:
  error:
    path: /error
    whitelabel:
      enabled: false
spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://localhost:3306/website
    name: website
  webflux:
    static-path-pattern: /static/**