server:
  port: 443
  redirection:
    port: 80
  error:
    path: /error
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/blog.p12
    key-store-password: ENC(ATt/mI8592l6T2OOC7lRPkG/6tg7+tAh7eqhEwhdAc7ZdLVjAnGz20xm8blTxwLP)
    key-alias: ENC(YgtsiJELvr96dZpiih3TT0r6rOa8oXGZCHxLxy7Vph11tGQvP6atukjor/f+EDev)
    enabled: true
spring:
  profiles:
    active: dev
  thymeleaf:
    reactive:
      max-chunk-size: 8192
cache:
  expiration:
    duration: 10M