spring:
  r2dbc:
    username: ENC(nt73AnNWj7nzGebX2BgQQijwSPZ9gnuJwaF2yUMsOo14wavJyklLDQSXqKmV7eKh)
    password: ENC(ZzhZ4C0cQPor06vARSw6NSOItke51i+Bzn4BShtEe9QG/uLSFdAXQFmRhk6JltOe)
    url: ENC(HL0ZaIITA8Jyk0Pya7jhpjvClsOsXGHCB96blXOT3E75Hpg3wArkNqKJiEc1TRZc+C/xCfU2PqJK0Hb3DfT3hWb5kM5WkEhF0+N5IjsfjPcxZjj40InH2aNmI/DSnUdwo3itZsA24PCLbCgjIzAtIQ==)
logging:
  level:
    root: error