server:
  error:
    path: /error
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  webflux:
    static-path-pattern: /static/**
  thymeleaf:
    reactive:
      max-chunk-size: 8192